apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-same-namespace
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: qket-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowedNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
        {{- end }}
      ports:
        - port: {{ .Values.networkPolicy.port }}
